name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry==1.8.3

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint
        run: |
          poetry run ruff .
          poetry run black --check .
          poetry run isort --check-only .

      - name: Type check
        run: poetry run mypy src

      - name: Run tests
        run: poetry run pytest -q
